name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create cache and install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: latest
          cache: "pnpm"

      - name: Setup pnpm
      - uses: pnpm/action-setup@v2.2.2
        id: pnpm-install
        with:
          version: latest

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        id: pnpm-cache-setup
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - if: ${{ steps.pnpm-cache-setup.outputs.cache-hit == 'false' }}
        name: Restore pnpm cache (Cache miss)
        continue-on-error: true
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
